print('Shapes')
print('--------------------------------------------')
print('          ')

print('PARALLELOG')
print('A        R')
print(' R        A')
print('  ALLELOGRAM')

print('          ')
print('  APEZO ')
print(' R     I')
print('TRAPEZOID')
print('          ')

print('RECTANGLE')
print('E       L')
print('C       G')
print('T       N')
print('A       A')
print('N       T')
print('G       C')
print('L       E')
print('ELGNATCER')

print('          ')
print('   D')
print('  III')
print(' AAAAA')
print('MMMMMMM')
print(' OOOOO')
print('  NNN')
print('   D')

print('          ')
print('--------------------------------------------')
print('My Initials')
print('          ')

print('*        *      ')
print('*        *      ')
print('*        *      ')
print('*        *      ')
print('*        *      ')
print('*        *      ')
print('*******  *******')